version: 0.0
os: linux
files:
  - source: ./index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: ./install.sh
      timeout: 300
      runas: root
    - location: ./start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./stop.sh
      timeout: 300
      runas: root
