version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
BeforeInstall:
  - location: scripts/before.sh
    timeout: 300
    runas: root
ApplicationStop:
  - location: scripts/stop.sh
    timeout: 300
    runas: root
